---
title: "kappa 60"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(devtools, quietly = TRUE)

load_all()

## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")
```

```{css "css-setup", echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

```{r "kappa167"}
#| eval: false
#| include: true

anchor <- c(30, 90, 120, 150)
bsk_knots <- c(50, 100, 150)
mlmf <- "log_outcome ~ surgery_type + patient_gender + adi_value +
                      adi_value:log_baseline + primary_payer + 
                      bmi + patient_age +
                      patient_age:log_baseline + log_baseline + t0"
gf <- "log_outcome ~ cs(time, df = 3)"
gs <- "~ cs(time, df = 1)"

lmf <- "log_outcome ~ as.factor(time) + surgery_type + patient_gender +
                      adi_value + adi_value:log_baseline + primary_payer +
                      bmi + patient_age +
                      patient_age:log_baseline + log_baseline + t0"

e_k60_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "euclidean",
                        match_number = 60)

e_k60_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "euclidean",
                        match_number = 60)

m_k60_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_number = 60)

m_k60_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_number = 60)

m_a90_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_alpha = 0.90)

m_a90_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_alpha = 0.90)

save(e_k60_mlm, e_k60_slm, 
     m_k60_mlm, m_k60_slm, 
     file = paste0("figure/tsa_12_kappa60_relationship_", Sys.Date(), ".Rdata"))
```

```{r "summarization_k60"}

load("figure/tsa_12_kappa60_relationship_2024-01-14.Rdata")

meanout <- function(dataset){
  # browser()
  result0 <- dataset %>%
    as.data.frame() %>%
    mutate(mse = bias^2) 
  result1 <- result0 %>%
    colMeans() %>%
    unlist()
  return(result1)}


result_ek60s <- map(e_k60_slm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

result_ek60m <- map(e_k60_mlm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

result_mk60s <- map(m_k60_slm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

result_mk60m <- map(m_k60_mlm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

## there is no target without any matches
result_ma80s <- map(m_a80_slm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
  
## there are 8 targets without any matches
result_ma80m <- map(m_a80_mlm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
result_ma80m[grep("Error", result_ma80m)] <- NULL
result_ma80m <- result_ma80m %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()


result_ma90m <- map(m_a90_mlm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
result_ma90m[grep("Error", result_ma90m)] <- NULL
result_ma90m <- result_ma90m %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()


result_ma90s <- map(m_a90_slm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
result_ma90s[grep("Error", result_ma90s)] <- NULL
result_ma90s <- result_ma90s %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()


result_ma95s <- map(m_a95_slm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
result_ma95s[grep("Error", result_ma95s)] <- NULL
result_ma95s <- result_ma95s %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

result_ma95m <- map(m_a95_mlm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
result_ma95m[grep("Error", result_ma95m)] <- NULL
result_ma95m <- result_ma95m %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()


```

```{r "final_table",  class.output="scroll-100"}
rbind(Ek60_SLM = result_ek60s, 
      Ek60_MLM = result_ek60m,
      Mk60_SLM = result_mk60s, 
      Mk60_MLM = result_mk60m,
      Ma80_SLM = result_ma80s,
      Ma90_SLM = result_ma90s,
      Ma95_SLM = result_ma95s,
      Ma80_MLM = result_ma80m,
      Ma90_MLM = result_ma90m,
      Ma95_MLM = result_ma95m) %>%
  as.data.frame() %>% 
  rownames_to_column("methods") %>%
  separate("methods", into = c("Criteria", "LM"))
```
