---
title: "Ek50 and Mk50 (Pulication)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(devtools, quietly = TRUE)

load_all()

## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")
```

```{css "css-setup", echo=FALSE}
.scroll-100 {
  max-height: 300px;
  max-width: 1000px;
  overflow-y: auto;
  background-color: inherit;
}
```

## Euclidean distance and Mahalanobis distance

```{r "kappa167"}
#| eval: false
#| include: true
#| error: true
#| warning: true
#| hide: true

anchor <- c(14, 30, 60, 90)
bsk_knots <- c(50, 100, 150, 200)
mlmf <- "log_outcome ~ surgery_type + patient_gender + adi_value +
                      adi_value:log_baseline + primary_payer + 
                      bmi + patient_age +
                      patient_age:log_baseline + log_baseline + t0"
gf <- "log_outcome ~ cs(time, df = 3)"
gs <- "~ cs(time, df = 1)"

lmf <- "log_outcome ~ as.factor(time) + surgery_type + patient_gender +
                      adi_value + adi_value:log_baseline + primary_payer +
                      bmi + patient_age +
                      patient_age:log_baseline + log_baseline + t0"

e_k50_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "euclidean",
                        match_number = 50)

e_k50_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "euclidean",
                        match_number = 50)

m_k50_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_number = 50)

m_k50_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_number = 50)

m_a90_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_alpha = 0.90)

m_a95_mlm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "mlm",
                        linear_formula = mlmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_alpha = 0.95)

m_a95_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_alpha = 0.95)

m_a90_slm <- people_like_us(train_data = tsa_train,
                        test_data = tsa_test,
                        anchor_time = anchor,
                        brokenstick_knots = bsk_knots,
                        linear_model = "lm",
                        linear_formula = lmf,
                        gamlss_formula = gf,
                        gamlss_sigma = gs,
                        tmin = 0,
                        tmax = 100,
                        id_var = "id",
                        outcome_var = "log_outcome",
                        time = "time",
                        weight = FALSE,
                        match_plot = FALSE,
                        predict_plot = FALSE,
                        match_methods = "mahalanobis",
                        match_alpha = 0.9)

save(e_k50_mlm, e_k50_slm, 
     m_k50_mlm, m_k50_slm, 
     m_a95_slm, m_a95_mlm,
     m_a95_slm, m_a90_mlm,
     file = paste0("figure/tsa_18_kappa50_relationship_", Sys.Date(), ".Rdata"))
```

For Mahalanobis distance, we have some target with no matches at all. This is not include due to we would not include the results of Mahalanobis distance into this paper.

## Summary for the Results

```{r "summarization_k50"}

load("figure/tsa_18_kappa50_relationship_2024-01-31.Rdata")

meanout <- function(dataset){
  # browser()
  result0 <- dataset %>%
    as.data.frame() %>%
    mutate(mse = bias^2) 
  result1 <- result0 %>%
    colMeans() %>%
    unlist()
  return(result1)}

all_out <- function(dataset){

  result0 <- dataset %>%
    as.data.frame() %>%
    mutate(mse = bias^2) 
  return(result0)}
```

```{r "mean_all"}
#| include: false
#| error: true
#| warning: false
#| hide: true

mean_result_ek50s <- map(e_k50_slm, "centiles_observed") %>% 
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
all_result_ek50s <- map(e_k50_slm, "centiles_observed") %>% 
  map_dfr(~try(all_out(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
mean_result_ek50m <- map(e_k50_mlm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
all_result_ek50m <- map(e_k50_mlm, "centiles_observed") %>%
  map_dfr(~try(all_out(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
mean_result_mk50s <- map(m_k50_slm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
all_result_mk50s <- map(m_k50_slm, "centiles_observed") %>%
  map_dfr(~try(all_out(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
mean_result_mk50m <- map(m_k50_mlm, "centiles_observed") %>%
  map_dfr(~try(meanout(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
all_result_mk50m <- map(m_k50_mlm, "centiles_observed") %>%
  map_dfr(~try(all_out(.))) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

mean_result_ma90m <- map(m_a90_mlm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
mean_result_ma90m[grep("Error", mean_result_ma90m)] <- NULL
mean_result_ma90m <- mean_result_ma90m %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
# mean_result_ma90s <- map(m_a90_slm, "centiles_observed") %>%
#   map(~try(meanout(.)) %>% unlist()) 
# mean_result_ma90s[grep("Error", mean_result_ma90s)] <- NULL
# mean_result_ma90s <- mean_result_ma90s %>%
#   map_dfr(~t(.) %>% as.data.frame()) %>%
#   dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
#   colMeans()
# mean_result_ma95m <- map(m_a95_mlm, "centiles_observed") %>%
#   map(~try(meanout(.)) %>% unlist()) 
# mean_result_ma95m[grep("Error", mean_result_ma95m)] <- NULL
# mean_result_ma95m <- mean_result_ma95m %>%
#   map_dfr(~t(.) %>% as.data.frame()) %>%
#   dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
#   colMeans()
mean_result_ma95s <- map(m_a95_slm, "centiles_observed") %>%
  map(~try(meanout(.)) %>% unlist()) 
mean_result_ma95s[grep("Error", mean_result_ma95s)] <- NULL
mean_result_ma95s <- mean_result_ma95s %>%
  map_dfr(~t(.) %>% as.data.frame()) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()

all_result_ma90m <- map(m_a90_mlm, "centiles_observed") %>%
  map(~try(all_out(.))) 
all_result_ma90m[grep("Error", all_result_ma90m)] <- NULL
all_result_ma90m <- all_result_ma90m %>%
  map_dfr(~as.data.frame(.)) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
# all_result_ma90s <- map(m_a90_slm, "centiles_observed") %>%
#   map(~try(all_out(.))) 
# all_result_ma90s[grep("Error", all_result_ma90s)] <- NULL
# all_result_ma90s <- all_result_ma90s %>%
#   map_dfr(~as.data.frame(.)) %>%
#   dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
#   colMeans()
# all_result_ma95m <- map(m_a95_mlm, "centiles_observed") %>%
#   map(~try(all_out(.))) 
# all_result_ma95m[grep("Error", all_result_ma95m)] <- NULL
# all_result_ma95m <- all_result_ma95m %>%
#   map_dfr(~as.data.frame(.)) %>%
#   dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
#   colMeans()
all_result_ma95s <- map(m_a95_slm, "centiles_observed") %>%
  map(~try(all_out(.))) 
all_result_ma95s[grep("Error", all_result_ma95s)] <- NULL
all_result_ma95s <- all_result_ma95s %>%
  map_dfr(as.data.frame) %>%
  dplyr::select(coverage50, coverage80, coverage90, bias, mse) %>%
  colMeans()
```

```{r "final_table",  class.output="scroll-100"}
options(scipen=1, digits=4)
result18_nw <- 
  rbind(meanEk50_SLM = mean_result_ek50s, 
        # allEk50_SLM = all_result_ek50s, 
        meanEk50_MLM = mean_result_ek50m,
        # allEk50_MLM = all_result_ek50m,
        meanMk50_SLM = mean_result_mk50s,
        # allMk50_SLM = all_result_mk50s, 
        meanMk50_MLM = mean_result_mk50m) %>%
        # allMk50_MLM = all_result_mk50m) %>%
  as.data.frame() %>% 
  rownames_to_column("methods") %>%
  separate("methods", into = c("Methods", "LM"))


result19_nw <- 
  rbind(meanEk50_SLM = mean_result_ek50s, 
        meanEk50_MLM = mean_result_ek50m) %>%
        # mean_Ma90_SLM = mean_result_ma90s,
        # meanMa90_MLM = mean_result_ma90m,
        # allMa90_MLM = all_result_ma90m,
        # meanMa95_SLM = mean_result_ma95s,
        # mean_Ma95_MLM = mean_result_ma95m,
        # all_Ma90_SLM = all_result_ma90s,
        # all_Ma95_MLM = all_result_ma95m,
        # allMa95_SLM = all_result_ma95s)%>%
  as.data.frame() %>% 
  rownames_to_column("methods") %>%
  separate("methods", into = c("Methods", "LM"))

result18_nw
result19_nw
```

<!-- This is very confusing, that the $ALL$ and $MEAN$ are performed differently in $\kappa$ and $\alpha$ -->

<!-- The $ALL$ has lower MSE and comparable MAD to the best of $E_{\kappa=50}$ -->

<!-- Currently we have so many things to compare: -->

<!-- -   $\kappa$ and $\alpha$ -->

<!-- -   $\alpha$ large or small -->

<!-- -   $ALL$ or $MEAN$ -->

<!-- -   $E$ and $M$, $ST$ is out -->

<!-- -   single and multiple linear model -->

<!-- -   weighted and unweighted -->

<!-- This is a lot of things to compare, and we need to be careful about the interpretation of the results. -->
