# Working log {.unnumbered}

Here is the Future work for TSA and Randy's thesis

## 20231101

1.  Including other features and outcomes for matching

2.  Using both pain for informative outcome for outcome inference

    2\*. pain and dash two outcomes

3.  ✅ 365 days cut off this is the last step of data cleaning

4.  ✅ Insurance company, and the worker report worse

5.  ✅ Cleaning multiple surgeries

-   filter out the patient with only one

-   filter out the two situations

    -   gap between the two surgeries are short or with few outcomes

    -   two adjacent surgeries without outcomes in between

    -   the second surgery without any further outcomes after

## 20231106

6.  ✅ Cleaning the pain dataset

7.  ✅ Table or histogram for the outcome number, timemax, and pain

## 20231109

8.  How to use the tsa data.

    -   filter the patients with the first outcome in a week after surgery

    -   use imputation inla-rw or inla-bspline as the baseline

    -   ask Stef whether brokenstick or multiple-imputation is powerful enough to provide

    -   test on the patients with first outcome in a week (pick out the patients)

9.  ✅ The pain and outcome at the same time ??? - most with both outcomes, very few no at the same time

10. only keep the first surgery for every one

11. the baseline will be `what ever the first outcome value is` and include the time gap between surgery and the first outcome

## 20231122-29

12. clean the patients with two and three surgeries

13. remove the second surgery for patients

14. filter out patient with fewer than 3 visits

15. filter out the time over a year

## 20231204

Things need to be fixed

1.  the matching plots are all-dataset-level together, but predictive plots are individual in level

2.  to add other matching distance and weights

3.  decide which variables are included into the lm() model

4.  the memory and speed for the function, a clean version for speed-up functions. **overwrite the objects**

## 20240109

1.  ignore the $M_\alpha$ currently, focus the relationship between $E_kappa$ and $M_\kappa$

2.  finally find the reason why the $\alpha$ does not work, missing values in outcome

3.  try to use multiple linear regression and generalized least square

4.  think about the relationship between `multi-lm`, `lm`, and `gls`

5.  the relationship between $\kappa$ and $\alpha$, best guesses in the `multi-lm` and `gls` cases

6.  show Jeremy the results, in next meeting

## 20240118

1.  including weights into the final model

2.  \*\*to be checked\*\* remove the self paid, and the select health and workers comp.

3.  how did we calculate the coverage and bias and all the things, the symmetric

4.  $\kappa$ the cross-validation, $\alpha$ cross validation

5.  the quantile of the cutoff; this programming the $\alpha$ cut off

6.  14 days is the anchor 30 60 90

7.  bsk using another setup for the boundary. seq(10, 120, by =10), 120 300 every 40.

8.  the curve in the region, the portion instead of mean of means

9.  the entire trajectory, take the portion across the individuals, 0.5, 0.85 or 0.9, 0.95

10. coverage and the kappa60 rerun and see how things go

## 20240212-22

1.  the coverage and the kappa50 rerun and for ST and Euclidean

2.  ask EJC whether we want to publish the package with the paper

3.  merge the brokenstick and lm into lmm, and use JMbayes dynamic prediction

4.  add the true single time ST people-like-me methods

## 20240320

1.  add the surgical date and follow-up time into the table1 (for the descriptives)

2.  linear model used the single linear model or multiple model.

## 2024

\[\] committee meeting date 21 24 25 of May 27 28th

\[\] the proposal for the PhD

\[\] asking Brandie for the member out of the University

\[\] send email to Stef by Monday.
