---
title: "Cross validation (Publication)"
---


```{r}
#| label: "kappa4_100_slm_plot_15"
#| fig-cap: Cross validation for kappa
#| fig-subcap-location: top
#| fig-width: 4
#| fig-height: 2
#| fig-subcap:
#| - "CV_kappa4_100SLM_BIAS"
#| - "CV_kappa4_100SLM_MSE"
#| - "CV_kappa4_100SLM_CR50"
#| - "CV_kappa4_100SLM_CR80"
#| - "CV_kappa4_100SLM_CR90"
#| warning: false
#| layout-ncol: 2

kappa4_100_slm_bias <- kappa4_100_slm %>%
  ggplot() +
  geom_line(aes(x = kappa, y = bias), color = "darkgreen") 
kappa4_100_slm_mse <- kappa4_100_slm %>%
  ggplot() +
  # geom_line(aes(x = kappa, y = bias), color = "blue") +
  geom_line(aes(x = kappa, y = mse), color = "indianred") 
  # scale_y_continuous("Bias", 
  #   sec.axis = sec_axis(~ ., name = "MSE"))
kappa4_100_slm_cr50 <- kappa4_100_slm %>%
  ggplot() +
  geom_line(aes(x = kappa, y = coverage50), color = "blue1") 
kappa4_100_slm_cr80<- kappa4_100_slm %>%
  ggplot() +
  # geom_line(aes(x = kappa, y = bias), color = "blue") +
  geom_line(aes(x = kappa, y = coverage80), color = "blue3") 
kappa4_100_slm_cr90<- kappa4_100_slm %>%
  ggplot() +
  # geom_line(aes(x = kappa, y = bias), color = "blue") +
  geom_line(aes(x = kappa, y = coverage90), color = "blue4")


kappa4_100_slm_bias + theme_bw() + theme(legend.position = "none")
kappa4_100_slm_mse + theme_bw() + theme(legend.position = "none")
kappa4_100_slm_cr50 + theme_bw() + theme(legend.position = "none")
kappa4_100_slm_cr80 + theme_bw() + theme(legend.position = "none")
kappa4_100_slm_cr90 + theme_bw() + theme(legend.position = "none")
```

### The MLM

probably will use 50 to 60 as the final matches criterion.

```{r}
#| label: "kappa4_100_mlm_15"

load("new2_tsa_15_table_kappa1_cross_validation_2024-04-08 13:38:46.Rdata")
kappa4_100_mlm <- rbind(map_dfr(result_kappa1, ~unlist(., recursive = FALSE))) %>%
  as.data.frame() %>%
  mutate(kappa = seq(4, 100, by = 2)) %>%
  dplyr::select(kappa, everything())
```

```{r}
#| label: "kappa4_100_mlm plot_15"
#| fig-cap: Cross validation for kappa
#| fig-subcap-location: top
#| fig-width: 4
#| fig-height: 2
#| fig-subcap:
#| - "CV_kappa4_100MLM_BIAS"
#| - "CV_kappa4_100MLM_MSE"
#| - "CV_kappa4_100MLM_CR50"
#| - "CV_kappa4_100MLM_CR80"
#| - "CV_kappa4_100MLM_CR90"
#| warning: false
#| layout-ncol: 2


kappa4_100_mlm_bias <- kappa4_100_mlm %>%
  ggplot() +
  geom_line(aes(x = kappa, y = bias), color = "darkgreen") 
kappa4_100_mlm_mse <- kappa4_100_mlm %>%
  ggplot() +
  # geom_line(aes(x = kappa, y = bias), color = "blue") +
  geom_line(aes(x = kappa, y = mse), color = "indianred") 
  # scale_y_continuous("Bias", 
  #   sec.axis = sec_axis(~ ., name = "MSE"))
kappa4_100_mlm_cr50 <- kappa4_100_mlm %>%
  ggplot() +
  geom_line(aes(x = kappa, y = coverage50), color = "blue1") 
kappa4_100_mlm_cr80<- kappa4_100_mlm %>%
  ggplot() +
  # geom_line(aes(x = kappa, y = bias), color = "blue") +
  geom_line(aes(x = kappa, y = coverage80), color = "blue3") 
kappa4_100_mlm_cr90<- kappa4_100_mlm %>%
  ggplot() +
  # geom_line(aes(x = kappa, y = bias), color = "blue") +
  geom_line(aes(x = kappa, y = coverage90), color = "blue4")

kappa4_100_mlm_bias + theme_bw() + theme(legend.position = "none")
kappa4_100_mlm_mse + theme_bw() + theme(legend.position = "none")
kappa4_100_mlm_cr50 + theme_bw() + theme(legend.position = "none")
kappa4_100_mlm_cr80 + theme_bw() + theme(legend.position = "none")
kappa4_100_mlm_cr90 + theme_bw() + theme(legend.position = "none")

```

<!-- ## Cross-validation for different $\kappa$ values smaller brokenstick knots -->

<!-- ### The SLM -->

<!-- The setup for this PLM: -->

<!-- -   anchor \<- c(14, 30, 60, 90) including 14 as the anchor -->

<!-- -   bsk_knots \<- c(50, 100, 150, 200) relatively reasonable -->

<!-- -   kappa1 \<- seq(10, 200, by = 10), it may seems not big enough to see the pattern -->

<!-- ```{r} -->

<!-- #| label: "kappa_load_17" -->

<!-- # load("figure/tsa_16_table_kappa1_cross_validation_2024-01-24 17:22:05.Rdata") -->

<!-- # load("figure/tsa_16_table_kappa2_cross_validation_2024-01-24 18:07:14.Rdata") -->

<!-- load("figure/tsa_17_table_simple_bks_slm_cross_validation_2024-01-24 22:40:50.Rdata") -->

<!-- # map_dfr(result_kappa0, ~unlist(., recursive = FALSE)) -->

<!-- kappa4_100_slm <- rbind(map_dfr(result_kappa1, ~unlist(., recursive = FALSE))) %>% -->

<!--   as.data.frame() %>% -->

<!--   mutate(kappa = seq(10, 200, by = 10)) %>% -->

<!--   dplyr::select(kappa, everything()) -->

<!-- kappa4_100_slm -->

<!-- # map_dfr(result_kappa5, ~unlist(., recursive = FALSE)) -->

<!-- ``` -->

<!-- brokenstick model does affect the result, but not very much over the trend -->

<!-- ```{r} -->

<!-- #| label: "kappa4_100_slm_plot_17" -->

<!-- #| fig-cap: Cross validation for kappa -->

<!-- #| fig-subcap-location: top -->

<!-- #| fig-width: 4 -->

<!-- #| fig-height: 2 -->

<!-- #| fig-subcap: -->

<!-- #| - "CV_kappa4_100SLM_BIAS" -->

<!-- #| - "CV_kappa4_100SLM_MSE" -->

<!-- #| - "CV_kappa4_100SLM_CR50" -->

<!-- #| - "CV_kappa4_100SLM_CR80" -->

<!-- #| - "CV_kappa4_100SLM_CR90" -->

<!-- #| warning: false -->

<!-- #| layout-ncol: 2 -->

<!-- kappa4_100_slm_bias <- kappa4_100_slm %>% -->

<!--   ggplot() + -->

<!--   geom_line(aes(x = kappa, y = bias), color = "darkgreen")  -->

<!-- kappa4_100_slm_mse <- kappa4_100_slm %>% -->

<!--   ggplot() + -->

<!--   # geom_line(aes(x = kappa, y = bias), color = "blue") + -->

<!--   geom_line(aes(x = kappa, y = mse), color = "indianred")  -->

<!--   # scale_y_continuous("Bias",  -->

<!--   #   sec.axis = sec_axis(~ ., name = "MSE")) -->

<!-- kappa4_100_slm_cr50 <- kappa4_100_slm %>% -->

<!--   ggplot() + -->

<!--   geom_line(aes(x = kappa, y = coverage50), color = "blue1")  -->

<!-- kappa4_100_slm_cr80<- kappa4_100_slm %>% -->

<!--   ggplot() + -->

<!--   # geom_line(aes(x = kappa, y = bias), color = "blue") + -->

<!--   geom_line(aes(x = kappa, y = coverage80), color = "blue3")  -->

<!-- kappa4_100_slm_cr90<- kappa4_100_slm %>% -->

<!--   ggplot() + -->

<!--   # geom_line(aes(x = kappa, y = bias), color = "blue") + -->

<!--   geom_line(aes(x = kappa, y = coverage90), color = "blue4") -->

<!-- kappa4_100_slm_bias + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_slm_mse + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_slm_cr50 + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_slm_cr80 + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_slm_cr90 + theme_bw() + theme(legend.position = "none") -->

<!-- ``` -->

<!-- ### The MLM -->

<!-- probably will use 50 to 60 as the final matches criterion. -->

<!-- ```{r} -->

<!-- #| label: "kappa4_100_mlm_17" -->

<!-- load("figure/tsa_17_table_simple_bsk_mlm_cross_validation_2024-01-24 22:38:18.Rdata") -->

<!-- kappa4_100_mlm <- rbind(map_dfr(result_kappa2, ~unlist(., recursive = FALSE))) %>% -->

<!--   as.data.frame() %>% -->

<!--   mutate(kappa = seq(10, 200, by = 10)) %>% -->

<!--   dplyr::select(kappa, everything()) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- #| label: "kappa4_100_mlm plot_17" -->

<!-- #| fig-cap: Cross validation for kappa -->

<!-- #| fig-subcap-location: top -->

<!-- #| fig-width: 4 -->

<!-- #| fig-height: 2 -->

<!-- #| fig-subcap: -->

<!-- #| - "CV_kappa4_100MLM_BIAS" -->

<!-- #| - "CV_kappa4_100MLM_MSE" -->

<!-- #| - "CV_kappa4_100MLM_CR50" -->

<!-- #| - "CV_kappa4_100MLM_CR80" -->

<!-- #| - "CV_kappa4_100MLM_CR90" -->

<!-- #| warning: false -->

<!-- #| layout-ncol: 2 -->

<!-- kappa4_100_mlm_bias <- kappa4_100_mlm %>% -->

<!--   ggplot() + -->

<!--   geom_line(aes(x = kappa, y = bias), color = "darkgreen")  -->

<!-- kappa4_100_mlm_mse <- kappa4_100_mlm %>% -->

<!--   ggplot() + -->

<!--   # geom_line(aes(x = kappa, y = bias), color = "blue") + -->

<!--   geom_line(aes(x = kappa, y = mse), color = "indianred")  -->

<!--   # scale_y_continuous("Bias",  -->

<!--   #   sec.axis = sec_axis(~ ., name = "MSE")) -->

<!-- kappa4_100_mlm_cr50 <- kappa4_100_mlm %>% -->

<!--   ggplot() + -->

<!--   geom_line(aes(x = kappa, y = coverage50), color = "blue1")  -->

<!-- kappa4_100_mlm_cr80<- kappa4_100_mlm %>% -->

<!--   ggplot() + -->

<!--   # geom_line(aes(x = kappa, y = bias), color = "blue") + -->

<!--   geom_line(aes(x = kappa, y = coverage80), color = "blue3")  -->

<!-- kappa4_100_mlm_cr90<- kappa4_100_mlm %>% -->

<!--   ggplot() + -->

<!--   # geom_line(aes(x = kappa, y = bias), color = "blue") + -->

<!--   geom_line(aes(x = kappa, y = coverage90), color = "blue4") -->

<!-- kappa4_100_mlm_bias + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_mlm_bias + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_mlm_mse + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_mlm_cr50 + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_mlm_cr80 + theme_bw() + theme(legend.position = "none") -->

<!-- kappa4_100_mlm_cr90 + theme_bw() + theme(legend.position = "none") -->

<!-- ``` -->

<!-- ### SLM and MLM comparison -->

<!-- ```{r} -->

<!-- #| label: "comparison_17" -->

<!-- #| fig-cap: Cross validation for kappa -->

<!-- #| fig-subcap-location: top -->

<!-- #| fig-width: 4 -->

<!-- #| fig-height: 2 -->

<!-- #| fig-subcap: -->

<!-- #| - "CV_kappa4_100SLM_BIAS" -->

<!-- #| - "CV_kappa4_100MLM_BIAS" -->

<!-- #| - "CV_kappa4_100SLM_MSE" -->

<!-- #| - "CV_kappa4_100MLM_MSE" -->

<!-- #| warning: false -->

<!-- #| layout-ncol: 2 -->

<!-- kappa4_100_slm_bias + theme_bw() + theme(legend.position = "none") + ylim(0.45, 0.51) -->

<!-- kappa4_100_mlm_bias + theme_bw() + theme(legend.position = "none") + ylim(0.45, 0.51) -->

<!-- kappa4_100_slm_mse + theme_bw() + theme(legend.position = "none") + ylim(0.65, 0.85) -->

<!-- kappa4_100_mlm_mse + theme_bw() + theme(legend.position = "none") + ylim(0.65, 0.85) -->

<!-- # kappa4_100_mlm_cr50 + theme_bw() + theme(legend.position = "none") -->

<!-- # kappa4_100_mlm_cr80 + theme_bw() + theme(legend.position = "none") -->

<!-- # kappa4_100_mlm_cr90 + theme_bw() + theme(legend.position = "none") -->

<!-- ``` -->

<!-- Matching size of 50 seems a reasonable choice for the paper -->
